stages:
  process_modis_monthly_avgs:
    cmd: python src/modis/process_data.py -v
    deps:
      - src/modis/process_data.py

  get_modis_monthly_avgs:
    cmd: python src/modis/get_data.py
    deps:
      - src/modis/process_data.py
      - src/modis/get_data.py

  get_esa_worldcover:
    cmd: python src/esa_worldcover/get_esa_worldcover_data.py -vd
    deps:
      - src/esa_worldcover/get_esa_worldcover_data.py

  get_soilgrids:
    cmd: python src/soilgrids/get_soilgrids_data.py -vd
    deps:
      - src/soilgrids/get_soilgrids_data.py

  get_worldclim:
    cmd: python src/worldclim/get_worldclim_data.py
    deps:
      - src/worldclim/get_worldclim_data.py

  get_canopy_height:
    cmd: python src/canopy_height/get_canopy_height_data.py
    deps:
      - src/canopy_height/get_canopy_height_data.py

  get_vodca:
    cmd: python src/vodca/get_vodca_data.py
    deps:
      - src/vodca/get_vodca_data.py
