stages:
  process_modis_monthly_avgs:
    cmd: python src/modis/process_data.py -v
    deps:
      - src/modis/process_data.py
      - src/utils/gee.py

  get_modis_monthly_avgs:
    cmd: python src/modis/get_data.py
    deps:
      - src/modis/process_data.py
      - src/modis/get_data.py
    outs:
      - ${modis.out_dir}:
          persist: true
