modis:
  date_start: "2001-01-01"
  date_end: "2024-01-01"
  product: "MODIS/061/MOD09GA"
  bands:
    - "sur_refl_b01" # red
    - "sur_refl_b02" # NIR (841-876nm)
    - "sur_refl_b03" # blue
    - "sur_refl_b04" # green
    - "sur_refl_b05" # NIR (1230-1250nm)
  qa_band: "state_1km"
  nodata: -32768
  crs: "EPSG:4326"
  scale: 1000 # In meters for GEE export
  target: "gcs"
  bucket: "modis_monthly_avgs_1km"
  out_dir: data/modis/modis_sur_refl_monthly_avg_1km

esa_worldcover:
  collection_id: "ESA/WorldCover/v100"
  crs: "EPSG:4326"
  scale: 1000 # In meters for GEE export
  target: "gcs"
  bucket: "esa_worldcover"
  out_path: data/landcover/esa_worldcover_v100_1km/esa_worldcover_v100_1km.tif

soilgrids:
  collection_id: "projects/soilgrids-isric"
  soil_properties:
    - "bdod"
    - "cec"
    - "cfvo"
    - "clay"
    - "nitrogen"
    - "ocd"
    - "ocs"
    - "phh2o"
    - "sand"
    - "silt"
    - "soc"
  soil_stat: "mean"
  nodata: -32768
  crs: "EPSG:4326"
  scale: 1000 # In meters for GEE export
  target: "gcs"
  bucket: "panops_soilgrids"
  out_dir: data/soilgrids/soilgrids_v2-0_1km

worldclim:
  url: https://biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1_30s_bio.zip
  out_dir: data/worldclim

vodca:
  collection_base: "projects/sat-io/open-datasets/VODCA"
  bands:
    - "C-BAND"
    - "K-BAND"
    - "X-BAND"
  percentiles:
    - 5
    - 95
  crs: "EPSG:4326"
  scale: 1000 # In meters for GEE export
  target: "gcs"
  bucket: "panops_vodca"
  out_dir: "data/vodca/vodca_all-bands_mean-p5-p95_1km"

canopy_height:
  height_collection: "users/nlang/ETH_GlobalCanopyHeight_2020_10m_v1"
  sd_collection: "users/nlang/ETH_GlobalCanopyHeightSD_2020_10m_v1"
  nodata: 255
  crs: "EPSG:4326"
  scale: 1000 # In meters for GEE export
  target: "gcs"
  bucket: "panops_canopy_height"
  out_dir: "data/canopy_height/ETH_GlobalCanopyHeight_2020_v1_1km"
