modis:
  date_start: "2001-01-01"
  date_end: "2024-01-01"
  product: "MODIS/061/MOD09GA"
  bands:
    - "sur_refl_b01" # red
    - "sur_refl_b02" # NIR (841-876nm)
    - "sur_refl_b03" # blue
    - "sur_refl_b04" # green
    - "sur_refl_b05" # NIR (1230-1250nm)
  qa_band: "state_1km"
  crs: "EPSG:4326"
  scale: 1000 # In meters for GEE export
  target: "gcs"
  bucket: "modis_monthly_avgs_1km"
  out_dir: data/modis/modis_sur_refl_monthly_avg_1km
  output_path: data/modis/modis_monthly_avg_2000-2024_1km.zarr # zarr only
  log_file: logs/modis.log

esa_worldcover:
  collection_id: "ESA/WorldCover/v100"
  crs: "EPSG:4326"
  scale: 1000 # In meters for GEE export
  target: "gcs"
  bucket: "esa_worldcover"
  out_path: data/esa_worldcover/esa_worldcover_v100_1km.tif

soilgrids:
  collection_id: "projects/soilgrids-isric"
  soil_properties:
    - "bdod"
    - "cec"
    - "cfvo"
    - "clay"
    - "nitrogen"
    - "ocd"
    - "ocs"
    - "phh2o"
    - "sand"
    - "silt"
    - "soc"
  soil_stat: "mean"
  crs: "EPSG:4326"
  scale: 1000 # In meters for GEE export
  target: "gcs"
  bucket: "panops_soilgrids"
  out_dir: data/soilgrids

worldclim:
  url: https://biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1_30s_bio.zip
  out_dir: data/worldclim

canopy_height:
  height_collection: "users/nlang/ETH_GlobalCanopyHeight_2020_10m_v1"
  sd_collection: "users/nlang/ETH_GlobalCanopyHeightSD_2020_10m_v1"
  crs: "EPSG:4326"
  scale: 1000 # In meters for GEE export
  target: "gcs"
  bucket: "panops_canopy_height"
  out_dir: "data/canopy_height"
