paths:
  root: ${hydra:runtime.cwd}
  data: ${.root}/data
  raw_data: ${.data}/raw

external_datasets:
  to_download: [land_mask, worldclim, vodca_c, vodca_ku, vodca_x]
  vodca_base_url: https://zenodo.org/records/2575599/files
  land_mask:
    url: https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_land.zip
    odir: ${paths.raw_data}/masks
    simple_download: true
  worldclim:
    url: https://biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1_30s_bio.zip
    odir: ${paths.raw_data}/worldclim
    simple_download: true
  vodca_c:
    url: ${external_datasets.vodca_base_url}/VODCA_C-band_2002-2018_v01.0.0.zip
    odir: ${paths.raw_data}/vodca
    simple_download: true
  vodca_ku:
    url: ${external_datasets.vodca_base_url}/VODCA_Ku-band_1987-2017_v01.0.0.zip
    odir: ${paths.raw_data}/vodca
  vodca_x:
    url: ${external_datasets.vodca_base_url}/VODCA_X-band_1997-2018_v01.0.0.zip
    odir: ${paths.raw_data}/vodca

gee:
  land_mask_project: esa-land-cover